import { beforeEach, describe, expect, test, vi } from 'vitest';
const rpc = vi.hoisted(() => vi.fn());
vi.mock('../services/supabase', () => ({ supabase: { rpc }, supabaseConfigurationError: null }));
import { addJointWorkoutParticipant, completedJointWorkoutInput, createJointWorkout, defaultJointParticipantId, directPartnerRecipient, finishJointWorkout, getJointWorkoutDetail, jointParticipantInviteCapacity, jointRoutineImportPlan, listJointWorkoutPosts, respondToJointInvite, routineSnapshot, touchJointWorkoutPresence } from '../services/jointWorkouts';
const routine = { id: 'local-id', name: ' Upper ', muscleGroups: ['back', 'back'], createdAt: '', exercises: [{ id: 'exercise-id', name: ' Row ', muscleGroups: ['back'], loadMode: 'external-load' as const, loadUnit: 'kg' as const, variant: 'barbell', sets: [{ id: 'set-id', tipo: 1, weight: 80, reps: 8 }] }] };
describe('joint workout RPC boundary', () => { beforeEach(() => vi.clearAllMocks());
  test('sends only a local-ID-free routine snapshot when inviting a current connection', async () => { rpc.mockResolvedValue({ data: 'workout-1', error: null }); await expect(createJointWorkout('member-2', routine)).resolves.toBe('workout-1'); expect(routineSnapshot(routine)).toEqual({ name: 'Upper', muscleGroups: ['back'], exercises: [{ name: 'Row', muscleGroups: ['back'], loadMode: 'external-load', loadUnit: 'kg', variant: 'barbell', sets: [{ tipo: 1, weight: 80, reps: 8 }] }] }); expect(rpc).toHaveBeenCalledWith('create_joint_workout', { target: 'member-2', suggested_routine_input: routineSnapshot(routine) }); expect(JSON.stringify(routineSnapshot(routine))).not.toContain('local-id'); });
  test('adds distinct Bro or Partner participants through the session-scoped protected RPC', async () => { rpc.mockResolvedValue({ error: null }); await addJointWorkoutParticipant('workout-1', 'member-3'); expect(rpc).toHaveBeenCalledWith('add_joint_workout_participant', { workout_id: 'workout-1', target: 'member-3' }); });
  test('keeps receiver routine choice and completion privacy server-owned', async () => { const completed = completedJointWorkoutInput(routine, 60, [{ exerciseId: 'local-exercise', name: 'Row', muscleGroupIds: ['back'], sets: [{ setId: 'local-set', weight: 80, reps: 8, completed: true }] }]); rpc.mockResolvedValue({ error: null }); await respondToJointInvite('workout-1', true, routine); await respondToJointInvite('workout-2', true, routineSnapshot(routine)); await finishJointWorkout('workout-1', 'private', completed); expect(rpc).toHaveBeenNthCalledWith(1, 'respond_joint_workout_invite', { workout_id: 'workout-1', accepted: true, routine_input: routineSnapshot(routine) }); expect(rpc).toHaveBeenNthCalledWith(2, 'respond_joint_workout_invite', { workout_id: 'workout-2', accepted: true, routine_input: routineSnapshot(routine) }); expect(rpc).toHaveBeenNthCalledWith(3, 'finish_joint_workout', { workout_id: 'workout-1', visibility_input: 'private', completed_workout_input: completed }); expect(JSON.stringify(completed)).not.toContain('local-exercise'); });
  test('maps joint feed identity only without treating a participant workout as implicitly visible', async () => { rpc.mockResolvedValue({ data: [{ id: 'workout-1', created_at: '2026-08-02T00:00:00Z', participants: [{ id: 'member-2', alias: 'Bro', avatar_id: 'capigirl', status: 'completed' }] }], error: null }); await expect(listJointWorkoutPosts()).resolves.toEqual([{ id: 'workout-1', createdAt: '2026-08-02T00:00:00Z', participants: [{ id: 'member-2', alias: 'Bro', avatarId: 'capigirl', status: 'completed' }] }]); });
  test('updates only the caller presence through the protected RPC', async () => { rpc.mockResolvedValue({ error: null }); await touchJointWorkoutPresence('workout-1'); expect(rpc).toHaveBeenCalledWith('touch_joint_workout_presence', { workout_id: 'workout-1' }); });
  test('imports a suggested routine with deterministic local IDs before real execution', () => { const plan = jointRoutineImportPlan('joint-workout:1', 'member-1', routineSnapshot(routine)); expect(plan.recipient).toBe('member-1'); expect(plan.routines[0].id).toBe('joint:joint-workout1:routine'); expect(plan.definitions[0].source).toEqual({ kind: 'custom', owner: 'member-1', originId: 'joint:joint-workout1:definition:0' }); expect(JSON.stringify(plan)).not.toContain('local-id'); });
  test('does not expose canned-action RPCs from the joint boundary', async () => {
    const boundary = await import('../services/jointWorkouts');
    expect(boundary).not.toHaveProperty('sendJointWorkoutAction');
    expect(boundary).not.toHaveProperty('listJointWorkoutActions');
  });
  test('keeps post detail participants when the server includes the required status projection', async () => { rpc.mockResolvedValue({ data: { id: 'workout-1', suggested_routine: routineSnapshot(routine), created_at: '2026-08-02T00:00:00Z', completed_at: '2026-08-02T01:00:00Z', participants: [{ id: 'member-2', alias: 'Partner', avatar_id: 'capigirl', status: 'completed', relationship_kind: 'partner' }] }, error: null }); await expect(getJointWorkoutDetail('workout-1')).resolves.toMatchObject({ id: 'workout-1', completedAt: '2026-08-02T01:00:00Z', participants: [{ id: 'member-2', status: 'completed', relationshipKind: 'partner' }] }); });
  test('keeps an omitted inviter routine omitted and selects only one direct Partner for detail chat', async () => { rpc.mockResolvedValue({ data: { id: 'workout-1', suggested_routine: null, created_at: '2026-08-02T00:00:00Z', participants: [{ id: 'partner-1', alias: 'Partner', avatar_id: 'capigirl', status: 'active', relationship_kind: 'partner' }] }, error: null }); const workout = await getJointWorkoutDetail('workout-1'); expect(workout?.suggestedRoutine).toBeUndefined(); expect(directPartnerRecipient(workout ?? null)).toBe('partner-1'); expect(directPartnerRecipient({ ...workout!, participants: [...workout!.participants, { id: 'bro-1', alias: 'Bro', avatarId: 'capigirl', status: 'active', relationshipKind: 'bro' }] })).toBe('partner-1'); expect(directPartnerRecipient({ ...workout!, participants: [...workout!.participants, { id: 'partner-2', alias: 'Partner 2', avatarId: 'capigirl', status: 'active', relationshipKind: 'partner' }] })).toBeNull(); });
  test('counts declined invitations against the server participant limit while preserving their UI identity', () => {
    expect(jointParticipantInviteCapacity([
      { id: 'bro-1', alias: 'Bro', avatarId: 'capigirl', status: 'active' },
      { id: 'declined-1', alias: 'Declined', avatarId: 'capigirl', status: 'declined' },
    ])).toBe(1);
  });
  test('defaults the joint detail selection to the post owner instead of participant order', () => {
    expect(defaultJointParticipantId({ id: 'workout-1', initiatorId: 'owner', createdAt: '', participants: [
      { id: 'member', alias: 'Member', avatarId: 'capigirl', status: 'active' },
      { id: 'owner', alias: 'Owner', avatarId: 'capiboy', status: 'completed' },
    ] })).toBe('owner');
  });
});
