import { beforeEach, describe, expect, test, vi } from 'vitest';
const rpc = vi.hoisted(() => vi.fn());
vi.mock('../services/supabase', () => ({ supabase: { rpc }, supabaseConfigurationError: null }));
import { addJointWorkoutParticipant, completedJointWorkoutInput, createJointWorkout, createJointParticipantComment, defaultJointParticipantId, directPartnerRecipient, finishJointWorkout, getJointParticipantPublicationDetail, getJointWorkoutDetail, inviteActiveWorkoutMember, jointParticipantInviteCapacity, jointRoutineImportPlan, listActiveWorkoutInviteCandidates, listJointParticipantComments, listJointWorkoutPosts, listJointWorkouts, respondToJointInvite, routineSnapshot, setJointParticipantReaction, touchJointWorkoutPresence, updateJointWorkoutLiveProgress } from '../services/jointWorkouts';
const routine = { id: 'local-id', name: ' Upper ', muscleGroups: ['back', 'back'], createdAt: '', exercises: [{ id: 'exercise-id', name: ' Row ', muscleGroups: ['back'], loadMode: 'external-load' as const, loadUnit: 'kg' as const, variant: 'barbell', sets: [{ id: 'set-id', tipo: 1, weight: 80, reps: 8 }] }] };
describe('joint workout RPC boundary', () => { beforeEach(() => vi.clearAllMocks());
  test('sends only a local-ID-free routine snapshot when inviting a current connection', async () => { rpc.mockResolvedValue({ data: 'workout-1', error: null }); await expect(createJointWorkout('member-2', routine)).resolves.toBe('workout-1'); expect(routineSnapshot(routine)).toEqual({ name: 'Upper', muscleGroups: ['back'], exercises: [{ name: 'Row', muscleGroups: ['back'], loadMode: 'external-load', loadUnit: 'kg', variant: 'barbell', sets: [{ tipo: 1, weight: 80, reps: 8 }] }] }); expect(rpc).toHaveBeenCalledWith('create_joint_workout', { target: 'member-2', suggested_routine_input: routineSnapshot(routine) }); expect(JSON.stringify(routineSnapshot(routine))).not.toContain('local-id'); });
  test('shares backoff relationships without exposing their local IDs', () => {
    const enriched = { ...routine, exercises: [{ ...routine.exercises[0], sets: [
      { id: 'set-a', tipo: 1, weight: 80, reps: 8, backoffGroupId: 'private-backoff-id', effortTarget: { kind: 'rir' as const, value: 2 as const } },
      { id: 'set-b', tipo: 2, weight: 70, reps: 10, backoffGroupId: 'private-backoff-id', effortTarget: { kind: 'rpe' as const, value: 8 as const } },
    ] }] };
    expect(routineSnapshot(enriched).exercises[0].sets).toEqual([
      { tipo: 1, weight: 80, reps: 8, effortTarget: { kind: 'rir', value: 2 }, backoffGroup: 0 },
      { tipo: 2, weight: 70, reps: 10, effortTarget: { kind: 'rpe', value: 8 }, backoffGroup: 0 },
    ]);
    expect(JSON.stringify(routineSnapshot(enriched))).not.toContain('private-backoff-id');
  });
  test('adds distinct Bro or Partner participants through the session-scoped protected RPC', async () => { rpc.mockResolvedValue({ error: null }); await addJointWorkoutParticipant('workout-1', 'member-3'); expect(rpc).toHaveBeenCalledWith('add_joint_workout_participant', { workout_id: 'workout-1', target: 'member-3' }); });
   test('invites only server-verified active circle members and accepts without sending a routine selector', async () => { const sharePayload = { version: 1 as const, routine: routineSnapshot(routine), mesocycle: { name: 'Block', goal: '', durationWeeks: 1, routines: [routineSnapshot(routine)], weeks: [[{ routineIndex: 0 }]] } }; const completed = completedJointWorkoutInput(routine, 60, [{ exerciseId: 'local-exercise', name: 'Row', muscleGroupIds: ['back'], sets: [{ setId: 'local-set', weight: 80, reps: 8, completed: true }] }], sharePayload); rpc.mockResolvedValueOnce({ data: 'workout-1', error: null }).mockResolvedValueOnce({ data: [{ id: 'member-2', alias: 'Bro', avatar_id: 'capigirl', presentation_theme_id: null, relationship_kind: 'bro', group_member_count: 2 }], error: null }).mockResolvedValue({ error: null }); await expect(inviteActiveWorkoutMember('member-2', routine)).resolves.toBe('workout-1'); await expect(listActiveWorkoutInviteCandidates()).resolves.toEqual([{ id: 'member-2', alias: 'Bro', avatarId: 'capigirl', themeId: null, relationshipKind: 'bro', groupMemberCount: 2 }]); await respondToJointInvite('workout-1', true); await finishJointWorkout('workout-1', 'private', completed); expect(rpc).toHaveBeenNthCalledWith(1, 'invite_active_workout_member', { target: 'member-2', suggested_routine_input: routineSnapshot(routine) }); expect(rpc).toHaveBeenNthCalledWith(2, 'list_active_workout_invite_candidates', {}); expect(rpc).toHaveBeenNthCalledWith(3, 'respond_joint_workout_invite', { workout_id: 'workout-1', accepted: true }); expect(completed.sharePayload).toEqual(sharePayload); expect(JSON.stringify(completed)).not.toContain('local-exercise'); });
  test('drops stale zero-member groups instead of presenting them as single active athletes', async () => { rpc.mockResolvedValue({ data: [{ id: 'member-2', alias: 'Finished athlete', avatar_id: 'capigirl', relationship_kind: 'bro', group_member_count: 0 }], error: null }); await expect(listActiveWorkoutInviteCandidates()).resolves.toEqual([]); });
  test('maps joint feed identity and its latest activity without treating a participant workout as implicitly visible', async () => { rpc.mockResolvedValue({ data: [{ id: 'workout-1', created_at: '2026-08-02T00:00:00Z', updated_at: '2026-08-02T01:00:00Z', participants: [{ id: 'member-2', alias: 'Bro', avatar_id: 'capigirl', status: 'completed' }] }], error: null }); await expect(listJointWorkoutPosts()).resolves.toEqual([{ id: 'workout-1', createdAt: '2026-08-02T00:00:00Z', updatedAt: '2026-08-02T01:00:00Z', participants: [{ id: 'member-2', alias: 'Bro', avatarId: 'capigirl', status: 'completed' }] }]); });
   test('updates only the caller presence through the protected RPC', async () => { rpc.mockResolvedValue({ error: null }); await touchJointWorkoutPresence('workout-1'); expect(rpc).toHaveBeenCalledWith('touch_joint_workout_presence', { workout_id: 'workout-1' }); });
   test('publishes aggregate live progress and maps only the approved participant projection', async () => { rpc.mockResolvedValueOnce({ error: null }).mockResolvedValueOnce({ data: [{ id: 'workout-1', created_at: '2026-08-10T10:00:00Z', participants: [{ id: 'member-2', alias: 'Bro', avatar_id: 'capigirl', status: 'active', live_state: 'resting', completed_exercises: 2, total_exercises: 5, completed_sets: 6, total_sets: 15, rest_ends_at: '2026-08-10T10:01:30Z', live_updated_at: '2026-08-10T10:00:00Z' }] }], error: null }); await updateJointWorkoutLiveProgress('workout-1', { state: 'resting', completedExercises: 2, totalExercises: 5, completedSets: 6, totalSets: 15, restSeconds: 90 }); await expect(listJointWorkouts()).resolves.toMatchObject([{ participants: [{ liveProgress: { state: 'resting', completedExercises: 2, totalExercises: 5, completedSets: 6, totalSets: 15, restEndsAt: '2026-08-10T10:01:30Z' } }] }]); expect(rpc).toHaveBeenNthCalledWith(1, 'update_joint_workout_live_progress', { workout_id: 'workout-1', state_input: 'resting', completed_exercises_input: 2, total_exercises_input: 5, completed_sets_input: 6, total_sets_input: 15, rest_seconds_input: 90 }); });
   test('uses the protected participant reaction RPC and accepts only a safe star state', async () => { rpc.mockResolvedValue({ data: { reacted: true, reaction_count: 2 }, error: null }); await expect(setJointParticipantReaction('workout-1', 'member-2', true)).resolves.toEqual({ reacted: true, reactionCount: 2 }); expect(rpc).toHaveBeenCalledWith('set_joint_participant_reaction', { workout_id: 'workout-1', target_id: 'member-2', reacted: true }); });
   test('uses protected participant comment RPCs and maps safe discussion projections', async () => { rpc.mockResolvedValueOnce({ data: [{ id: 'comment-1', author_alias: 'Bro', author_avatar_id: 'capigirl', author_theme_id: null, body: 'Great work!', created_at: '2026-08-08T10:00:00Z', is_author: true }], error: null }).mockResolvedValueOnce({ data: { id: 'comment-2', author_alias: 'Partner', author_avatar_id: 'capigirl', author_theme_id: null, body: 'Nice pace', created_at: '2026-08-08T10:01:00Z', is_author: false }, error: null }); await expect(listJointParticipantComments('workout-1', 'member-2')).resolves.toEqual([{ id: 'comment-1', authorAlias: 'Bro', authorAvatarId: 'capigirl', authorThemeId: null, body: 'Great work!', createdAt: '2026-08-08T10:00:00Z', isAuthor: true }]); await expect(createJointParticipantComment('workout-1', 'member-2', '  Nice pace  ')).resolves.toMatchObject({ id: 'comment-2', body: 'Nice pace' }); expect(rpc).toHaveBeenNthCalledWith(1, 'list_joint_participant_comments', { workout_id: 'workout-1', target_id: 'member-2' }); expect(rpc).toHaveBeenNthCalledWith(2, 'create_joint_participant_comment', { workout_id: 'workout-1', target_id: 'member-2', body_input: 'Nice pace' }); });
  test('imports a suggested routine with deterministic local IDs before real execution', () => { const plan = jointRoutineImportPlan('joint-workout:1', 'member-1', routineSnapshot(routine)); expect(plan.recipient).toBe('member-1'); expect(plan.routines[0].id).toBe('joint:joint-workout1:routine'); expect(plan.definitions[0].source).toEqual({ kind: 'custom', owner: 'member-1', originId: 'joint:joint-workout1:definition:0' }); expect(JSON.stringify(plan)).not.toContain('local-id'); });
  test('does not expose canned-action RPCs from the joint boundary', async () => {
    const boundary = await import('../services/jointWorkouts');
    expect(boundary).not.toHaveProperty('sendJointWorkoutAction');
    expect(boundary).not.toHaveProperty('listJointWorkoutActions');
  });
  test('keeps post detail participants when the server includes the required status projection', async () => { const sharePayload = { version: 1 as const, routine: routineSnapshot(routine), mesocycle: { name: 'Block', goal: '', durationWeeks: 1, routines: [routineSnapshot(routine)], weeks: [[{ routineIndex: 0 }]] } }; rpc.mockResolvedValueOnce({ data: { id: 'workout-1', suggested_routine: routineSnapshot(routine), created_at: '2026-08-02T00:00:00Z', completed_at: '2026-08-02T01:00:00Z', participants: [{ id: 'member-2', alias: 'Partner', avatar_id: 'capigirl', status: 'completed', relationship_kind: 'partner', workout: { routineName: 'Upper', durationSeconds: 60, exercises: [{ name: 'Row', muscleGroupIds: ['back'], sets: [{ weight: 80, reps: 8, completed: true }] }] }, share_payload: sharePayload }] }, error: null }).mockResolvedValueOnce({ data: { 'member-2': { reaction_count: 2, comment_count: 3, viewer_has_reacted: true } }, error: null }); await expect(getJointWorkoutDetail('workout-1')).resolves.toMatchObject({ id: 'workout-1', completedAt: '2026-08-02T01:00:00Z', participants: [{ id: 'member-2', status: 'completed', relationshipKind: 'partner', reactionCount: 2, commentCount: 3, viewerHasReacted: true, workout: { exercises: [{ sets: [{ weight: 80, reps: 8, completed: true }] }] }, sharePayload }] }); });
  test('builds a participant publication detail from the joint workout and discussion thread', async () => { const sharePayload = { version: 1 as const, routine: routineSnapshot(routine) }; rpc.mockResolvedValueOnce({ data: { id: 'workout-1', created_at: '2026-08-02T00:00:00Z', completed_at: '2026-08-02T01:00:00Z', participants: [{ id: 'member-2', alias: 'Partner', avatar_id: 'capigirl', status: 'completed', relationship_kind: 'partner', workout: { routineName: 'Upper', durationSeconds: 60, exercises: [{ name: 'Row', muscleGroupIds: ['back'], sets: [{ weight: 80, reps: 8, completed: true }] }] }, share_payload: sharePayload }] }, error: null }).mockResolvedValueOnce({ data: [{ id: 'comment-1', author_alias: 'Partner', author_avatar_id: 'capigirl', body: 'Great work!', created_at: '2026-08-02T02:00:00Z', is_author: false }], error: null }).mockResolvedValueOnce({ data: { 'member-2': { reaction_count: 2, comment_count: 1, viewer_has_reacted: true } }, error: null }); await expect(getJointParticipantPublicationDetail('workout-1', 'member-2')).resolves.toMatchObject({ id: 'joint:workout-1:member-2', reactionCount: 2, commentCount: 1, viewerHasReacted: true, comments: [{ id: 'comment-1', body: 'Great work!' }], sharePayload }); });
  test('keeps an omitted inviter routine omitted and selects only one direct Partner for detail chat', async () => { rpc.mockResolvedValueOnce({ data: { id: 'workout-1', suggested_routine: null, created_at: '2026-08-02T00:00:00Z', participants: [{ id: 'partner-1', alias: 'Partner', avatar_id: 'capigirl', status: 'active', relationship_kind: 'partner' }] }, error: null }).mockResolvedValueOnce({ data: {}, error: null }); const workout = await getJointWorkoutDetail('workout-1'); expect(workout?.suggestedRoutine).toBeUndefined(); expect(directPartnerRecipient(workout ?? null)).toBe('partner-1'); expect(directPartnerRecipient({ ...workout!, participants: [...workout!.participants, { id: 'bro-1', alias: 'Bro', avatarId: 'capigirl', status: 'active', relationshipKind: 'bro' }] })).toBe('partner-1'); expect(directPartnerRecipient({ ...workout!, participants: [...workout!.participants, { id: 'partner-2', alias: 'Partner 2', avatarId: 'capigirl', status: 'active', relationshipKind: 'partner' }] })).toBeNull(); });
  test('counts declined invitations against the server participant limit while preserving their UI identity', () => {
    expect(jointParticipantInviteCapacity([
      { id: 'bro-1', alias: 'Bro', avatarId: 'capigirl', status: 'active' },
      { id: 'declined-1', alias: 'Declined', avatarId: 'capigirl', status: 'declined' },
    ])).toBe(1);
  });
  test('defaults the joint detail selection to the post owner instead of participant order', () => {
    expect(defaultJointParticipantId({ id: 'workout-1', initiatorId: 'owner', createdAt: '', participants: [
      { id: 'member', alias: 'Member', avatarId: 'capigirl', status: 'active' },
      { id: 'owner', alias: 'Owner', avatarId: 'capiboy', status: 'completed' },
    ] })).toBe('owner');
  });
});
