import React from 'react';
import TestRenderer, { act } from 'react-test-renderer';
import { afterEach, expect, test, vi } from 'vitest';
const storage = vi.hoisted(() => ({ getItem: vi.fn(async () => null), setItem: vi.fn(async () => undefined), removeItem: vi.fn(async () => undefined) }));
vi.mock('@react-native-async-storage/async-storage', () => ({ default: storage }));
vi.mock('../context/ThemeContext', () => ({ useTheme: () => ({ theme: { text: '#FFF', textMuted: '#AAA', primary: '#0FA', glassBorder: '#333' } }) }));
vi.mock('../components/UI', () => ({ GlassButton: (props: Record<string, unknown>) => React.createElement('Button', props) }));
vi.mock('../components/ProceduralAtmosphere', () => ({ ProceduralAtmosphere: (props: Record<string, unknown>) => React.createElement('Scene', props) }));
import { ATMOSPHERES, getLocalAtmosphere, saveLocalAtmosphere } from '../hooks/useLocalAtmosphere';
import { AtmospherePicker } from '../components/AtmospherePicker';
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
let tree: TestRenderer.ReactTestRenderer | undefined;
afterEach(async () => { if (tree) act(() => tree!.unmount()); tree = undefined; vi.useRealTimers(); storage.setItem.mockResolvedValue(undefined); await saveLocalAtmosphere(null); });
test('persists only validated local IDs, rolls back rejected writes, and restores collection without wallet APIs', async () => {
  expect(ATMOSPHERES).toHaveLength(4);
  await saveLocalAtmosphere('local-forge');
  expect(storage.setItem).toHaveBeenLastCalledWith('gymbro:local-atmosphere:v1', 'local-forge');
  storage.setItem.mockRejectedValueOnce(new Error('disk full'));
  await expect(saveLocalAtmosphere('local-orbit')).rejects.toThrow('disk full');
  expect(getLocalAtmosphere()).toBe('local-forge');
  await saveLocalAtmosphere(null);
  expect(getLocalAtmosphere()).toBeNull();
  expect(storage.removeItem).toHaveBeenCalledWith('gymbro:local-atmosphere:v1');
});
test('mounts only selected preview, automatically ends it, and retains selection after failed activation', async () => {
  vi.useFakeTimers();
  await act(async () => { tree = TestRenderer.create(React.createElement(AtmospherePicker)); });
  const press = (label: string) => tree!.root.find((node) => String(node.type) === 'Pressable' && node.props.accessibilityLabel === label);
  expect(tree!.root.findAllByType('Scene' as React.ElementType)).toHaveLength(0);
  act(() => press('Previsualizar Forja').props.onPress());
  expect(tree!.root.findAllByType('Scene' as React.ElementType)).toHaveLength(1);
  act(() => press('Previsualizar Órbita').props.onPress());
  expect(tree!.root.findByType('Scene' as React.ElementType).props.id).toBe('local-orbit');
  act(() => { vi.advanceTimersByTime(12000); });
  expect(tree!.root.findAllByType('Scene' as React.ElementType)).toHaveLength(0);
  act(() => press('Previsualizar Aurora').props.onPress());
  storage.setItem.mockRejectedValueOnce(new Error('disk full'));
  await act(async () => { tree!.root.find((node) => String(node.type) === 'Button' && node.props.title === 'Usar Aurora en este dispositivo').props.onPress(); });
  expect(tree!.root.findAll((node) => String(node.type) === 'Text' && node.props.accessibilityRole === 'alert')).toHaveLength(1);
  expect(getLocalAtmosphere()).toBeNull();
  await act(async () => { tree!.root.find((node) => String(node.type) === 'Button' && node.props.title === 'Usar Aurora en este dispositivo').props.onPress(); });
  expect(getLocalAtmosphere()).toBe('local-aurora');
  await act(async () => { tree!.root.find((node) => String(node.type) === 'Button' && node.props.title === 'Usar fondo de mi colección').props.onPress(); });
  expect(getLocalAtmosphere()).toBeNull();
});
