import React from 'react';
import { act } from 'react-test-renderer';
import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import * as Reanimated from 'react-native-reanimated';
import { Share } from 'react-native';
import { findText, press, render, resetRuntimeHarness } from './helpers/runtimeHarness';
import { WorkoutVictory } from '../components/WorkoutVictory';
import type { ExperienceReceipt, RewardReceipt, WorkoutSession } from '../types';
const activity = vi.hoisted(() => ({ enabled: true }));
vi.mock('../hooks/useAnimationActivity', () => ({ useAnimationActivity: (enabled: boolean) => enabled && activity.enabled }));
const session: WorkoutSession = { id: 's', routineId: 'r', routineName: 'Upper', completedAt: '', durationSeconds: 360, restTimerSeconds: 60, exercises: [{ exerciseId: 'e', name: 'Press', sets: [{ setId: 'a', weight: 42, reps: 8, completed: true }, { setId: 'b', weight: 42, reps: 8, completed: false }] }] };
const experience: ExperienceReceipt = { attemptId: 's', earnedXp: 50, entries: [], progress: { level: 5, rank: 'Intermedio', xpIntoLevel: 20, xpForNextLevel: 287, totalXp: 820 } };
const rewards: RewardReceipt = { balance: 200, entries: [{ kind: 'contextual_record', amount: 75, breakdown: {} }], weekly: {} };
beforeEach(() => { resetRuntimeHarness(); activity.enabled = true; vi.clearAllMocks();
 // Match Reanimated's stable shared value identity across React renders.
 vi.spyOn(Reanimated, 'useSharedValue').mockImplementation((value: any) => React.useRef({ value }).current as any);
});
afterEach(() => { resetRuntimeHarness(); vi.useRealTimers(); vi.restoreAllMocks(); });
test('offers details immediately and removes all external sharing actions', () => {
 const details = vi.fn(); const tree = render(React.createElement(WorkoutVictory, { session, onDetails: details }));
 press(tree.root.findAllByProps({ accessibilityLabel: 'Ver entrenamiento' })[0]); expect(details).toHaveBeenCalledOnce();
 expect(JSON.stringify(tree.toJSON())).not.toMatch(/Compartir|Elegir destino|REPS/);
 expect(Share.share).not.toHaveBeenCalled();
});
test('reduced motion shows confirmed level and gems immediately with optional breakdown', () => {
 activity.enabled = false;
 const timing = vi.spyOn(Reanimated, 'withTiming');
 const tree = render(React.createElement(WorkoutVictory, { session, experience, rewards, celebrate: true }));
 expect(timing).not.toHaveBeenCalled();
 expect(JSON.stringify(tree.toJSON())).toContain('75 gemas ganadas');
 const bar = tree.root.find((node) => String(node.type) === 'View' && node.props.accessibilityRole === 'progressbar');
 expect(bar.props.accessibilityValue).toEqual({ min: 0, max: 287, now: 20 });
 expect(findText(tree.root, 'Nuevo rango: Intermedio')).toBeTruthy();
 press(tree.root.findAllByProps({ accessibilityLabel: 'Ver recompensas' })[0]);
 expect(findText(tree.root, 'Récord personal')).toBeTruthy();
});
test('plays once, increments level before counting gems, and never replays on focus', () => {
 vi.useFakeTimers();
 const timing = vi.spyOn(Reanimated, 'withTiming');
 const props = { session, experience, rewards, celebrate: true };
 const tree = render(React.createElement(WorkoutVictory, props));
 expect(findText(tree.root, '4')).toBeTruthy();
 act(() => { vi.advanceTimersByTime(1200); });
 expect(findText(tree.root, '5')).toBeTruthy();
 expect(findText(tree.root, '¡SUBISTE DE NIVEL!')).toBeTruthy();
 act(() => { vi.advanceTimersByTime(1200); });
 expect(vi.getTimerCount()).toBe(0);
 activity.enabled = false; act(() => tree.update(React.createElement(WorkoutVictory, props)));
 activity.enabled = true; act(() => tree.update(React.createElement(WorkoutVictory, props)));
 expect(timing).toHaveBeenCalledOnce();
 render(React.createElement(WorkoutVictory, { ...props, celebrate: false }));
 expect(timing).toHaveBeenCalledOnce();
});
test('pending receipts never look like confirmed zero rewards and timers stop on unmount', () => {
 vi.useFakeTimers();
 const tree = render(React.createElement(WorkoutVictory, { session, celebrate: true }));
 expect(findText(tree.root, 'Gemas pendientes de confirmación')).toBeTruthy();
 act(() => tree.update(React.createElement(WorkoutVictory, { session, experience, rewards, celebrate: true })));
 expect(vi.getTimerCount()).toBe(1);
 act(() => tree.unmount()); expect(vi.getTimerCount()).toBe(0);
});
