import React from 'react';
import { act } from 'react-test-renderer';
import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import * as Reanimated from 'react-native-reanimated';
import { Share } from 'react-native';
import { findButton, findText, press, render, resetRuntimeHarness } from './helpers/runtimeHarness';
import { WorkoutVictory } from '../components/WorkoutVictory';
import type { WorkoutSession } from '../types';
const activity = vi.hoisted(() => ({ enabled: true }));
vi.mock('../hooks/useAnimationActivity', () => ({ useAnimationActivity: (enabled: boolean) => enabled && activity.enabled }));
const session: WorkoutSession = { id: 's', routineId: 'r', routineName: 'Upper', completedAt: '', durationSeconds: 360, restTimerSeconds: 60, exercises: [{ exerciseId: 'e', name: 'Press', sets: [{ setId: 'a', weight: 42, reps: 8, completed: true }, { setId: 'b', weight: 42, reps: 8, completed: false }] }] };
beforeEach(() => { resetRuntimeHarness(); activity.enabled = true; vi.clearAllMocks(); });
afterEach(() => { resetRuntimeHarness(); vi.restoreAllMocks(); });
test('offers detail immediately and requires preview and explicit destination before system sharing', async () => {
  const details = vi.fn();
  const tree = render(React.createElement(WorkoutVictory, { session, celebrate: true, onDetails: details }));
  press(findButton(tree.root, 'Explorar mi entrenamiento'));
  expect(details).toHaveBeenCalledOnce();
  expect(Share.share).not.toHaveBeenCalled();
  press(findButton(tree.root, 'Compartir un resumen'));
  expect(findText(tree.root, 'Tú eliges dónde compartir')).toBeTruthy();
  expect(Share.share).not.toHaveBeenCalled();
  await act(async () => { findButton(tree.root, 'Elegir destino').props.onPress(); await Promise.resolve(); });
  expect(Share.share).toHaveBeenCalledWith({ message: expect.stringContaining('1/2 series') });
  expect(vi.mocked(Share.share).mock.calls[0][0]).not.toEqual(expect.objectContaining({ message: expect.stringContaining('42') }));
});
test('keeps factual final values with reduced motion and uses a safe zero-total progress range', () => {
  activity.enabled = false;
  const timing = vi.spyOn(Reanimated, 'withTiming');
  const tree = render(React.createElement(WorkoutVictory, { session: { ...session, exercises: [] }, celebrate: true }));
  expect(timing).not.toHaveBeenCalled();
  expect(findText(tree.root, 'Cada serie cuenta.')).toBeTruthy();
  const bar = tree.root.find((node) => String(node.type) === 'View' && node.props.accessibilityRole === 'progressbar');
  expect(bar.props.accessibilityValue).toMatchObject({ min: 0, max: 1, now: 0 });
  expect(findButton(tree.root, 'Compartir un resumen').props.disabled).not.toBe(true);
});
test('runs one coordinated sequence after delayed preference readiness, never on recap or reentry', () => {
  activity.enabled = false;
  const timing = vi.spyOn(Reanimated, 'withTiming');
  const tree = render(React.createElement(WorkoutVictory, { session, celebrate: true }));
  activity.enabled = true;
  act(() => tree.update(React.createElement(WorkoutVictory, { session, celebrate: true })));
  expect(timing).toHaveBeenCalledOnce();
  expect(timing).toHaveBeenCalledWith(1, expect.objectContaining({ duration: 1200 }));
  activity.enabled = false;
  act(() => tree.update(React.createElement(WorkoutVictory, { session, celebrate: true })));
  activity.enabled = true;
  act(() => tree.update(React.createElement(WorkoutVictory, { session, celebrate: true })));
  expect(timing).toHaveBeenCalledOnce();
  render(React.createElement(WorkoutVictory, { session, celebrate: false }));
  expect(timing).toHaveBeenCalledOnce();
});
