import React from 'react';
import TestRenderer, { act } from 'react-test-renderer';
import { expect, test, vi } from 'vitest';
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
const state = vi.hoisted(() => ({ importCatalogContent: vi.fn(), getWorkoutRecapDetail: vi.fn(), push: vi.fn(), recapImportPlan: vi.fn(() => ({ routines: [] })) }));
vi.mock('expo-router', () => ({ router: { push: state.push, back: vi.fn() }, useLocalSearchParams: () => ({ id: 'recap-1' }) }));
vi.mock('../context/AuthContext', () => ({ useAuth: () => ({ user: 'owner' }) }));
vi.mock('../context/SocialContext', () => ({ useSocial: () => ({ getWorkoutRecapDetail: state.getWorkoutRecapDetail }) }));
vi.mock('../context/DataContext', () => ({ useData: () => ({ importCatalogContent: state.importCatalogContent }) }));
vi.mock('../context/ThemeContext', () => ({ useTheme: () => ({ theme: { text: '#fff', textMuted: '#aaa' } }) }));
vi.mock('../components/WorkoutPublicationCard', () => ({ WorkoutPublicationCard: (props: any) => React.createElement('Publication', props) }));
vi.mock('../components/WorkoutRecapAnalysis', () => ({ WorkoutRecapAnalysis: () => null }));
vi.mock('../components/AppNavBar', () => ({ AppNavBar: () => null }));
vi.mock('../components/GlassCard', () => ({ GlassCard: ({ children }: any) => React.createElement('Card', null, children), ThemeBackground: ({ children }: any) => React.createElement('Background', null, children) }));
vi.mock('../components/UI', () => ({ GlassButton: (props: any) => React.createElement('Button', props), GlassInput: () => null }));
vi.mock('../services/workoutRecapFeed', () => ({ recapImportPlan: state.recapImportPlan, setWorkoutRecapReaction: vi.fn(), createWorkoutRecapComment: vi.fn() }));
vi.mock('../services/jointWorkouts', () => ({ getJointParticipantPublicationDetail: vi.fn(), setJointParticipantReaction: vi.fn(), createJointParticipantComment: vi.fn() }));
import Screen from '../app/social/recap/[id]';
test('own detail links to own profile and explicitly copies template only once', async () => {
  const payload = { version: 1, routine: { name: 'Upper', exercises: [], muscleGroups: [] } };
  state.getWorkoutRecapDetail.mockResolvedValue({ id: 'recap-1', authorAlias: 'Alex', authorId: 'owner', isAuthor: true, routineName: 'Upper', sharePayload: payload, templateAvailable: true, comments: [], reactionCount: 0 });
  let tree: TestRenderer.ReactTestRenderer;
  await act(async () => { tree = TestRenderer.create(React.createElement(Screen)); });
  await act(async () => tree!.root.findByType('Publication' as any).props.onProfilePress());
  expect(state.push).toHaveBeenCalledWith('/profile');
  await act(async () => tree!.root.findAllByProps({ title: 'Copiar rutina' })[0].props.onPress());
  expect(state.recapImportPlan).toHaveBeenCalledWith('recap-1', 'owner', payload, false);
  expect(state.importCatalogContent).toHaveBeenCalledOnce();
  expect(tree!.root.findAllByProps({ title: 'Rutina guardada' })[0].props.disabled).toBe(true);
  await act(async () => tree!.unmount());
});
