import { CatalogImportPlan, CompletedExercise, Routine, WorkoutRecapSharePayload } from '../types';
import { supabase, supabaseConfigurationError } from './supabase';
import { avatarIdOrDefault } from '../constants/avatars';

export type JointVisibility = 'public' | 'circle' | 'private';
export type JointParticipantStatus = 'invited' | 'active' | 'completed' | 'declined';
export type JointRoutine = NonNullable<WorkoutRecapSharePayload['routine']>;
export type JointCompletedWorkout = { routineName: string; durationSeconds: number; exercises: Array<{ name: string; muscleGroupIds: string[]; sets: Array<{ weight: number; reps: number; completed: boolean }> }> };
export type JointParticipant = { id: string; alias: string; avatarId: string; status: JointParticipantStatus; relationshipKind?: 'bro' | 'partner'; visibility?: JointVisibility; isSelf?: boolean; workout?: JointCompletedWorkout | null; canInviteBro?: boolean };
export type JointWorkout = { id: string; initiatorId?: string; suggestedRoutine: JointRoutine; createdAt: string; completedAt?: string | null; participants: JointParticipant[] };
export type JointActionKind = 'push' | 'nice_set' | 'finish_strong' | 'partner_proud';
export type JointAction = { id: string; senderId: string; recipientId: string; action: JointActionKind; createdAt: string };
export const JOINT_ACTION_LABELS: Record<JointActionKind, string> = { push: '¡Dale!', nice_set: '¡Buena serie!', finish_strong: '¡Terminá fuerte!', partner_proud: 'Orgulloso de vos' };

function client() { if (!supabase) throw new Error(supabaseConfigurationError ?? 'Supabase is unavailable.'); return supabase; }
function routineSnapshot(routine: Routine): JointRoutine {
  return { name: routine.name.trim(), muscleGroups: [...new Set(routine.muscleGroups)].sort(), exercises: routine.exercises.map((exercise) => ({ name: exercise.name.trim(), muscleGroups: [...new Set(exercise.muscleGroups)].sort(), loadMode: exercise.loadMode ?? exercise.definitionSnapshot?.loadMode ?? 'external-load', loadUnit: exercise.loadUnit ?? exercise.definitionSnapshot?.loadUnit ?? 'kg', variant: exercise.variant, sets: exercise.sets.map(({ tipo, weight, reps }) => ({ tipo, weight, reps })) })) };
}
function jointId(value: string) { return value.replace(/[^a-zA-Z0-9_-]/g, ''); }
export function jointRoutineImportPlan(workoutId: string, recipient: string, routine: JointRoutine): CatalogImportPlan {
  const prefix = `joint:${jointId(workoutId)}`;
  return { recipient, definitions: routine.exercises.map((exercise, index) => ({ id: `${prefix}:definition:${index}`, source: { kind: 'custom' as const, owner: recipient, originId: `${prefix}:definition:${index}` }, name: exercise.name, muscleGroups: exercise.muscleGroups, loadMode: exercise.loadMode, loadUnit: exercise.loadUnit, variant: exercise.variant, defaultSets: exercise.sets.map((set, setIndex) => ({ ...set, id: `${prefix}:set:${index}:${setIndex}` })) })), routines: [{ id: `${prefix}:routine`, name: routine.name, muscleGroups: routine.muscleGroups, createdAt: new Date().toISOString(), exercises: routine.exercises.map((exercise, index) => ({ id: `${prefix}:exercise:${index}`, definitionId: `${prefix}:definition:${index}`, catalogExerciseId: `${prefix}:definition:${index}`, name: exercise.name, muscleGroups: exercise.muscleGroups, loadMode: exercise.loadMode, loadUnit: exercise.loadUnit, variant: exercise.variant, sets: exercise.sets.map((set, setIndex) => ({ ...set, id: `${prefix}:set:${index}:${setIndex}` })) })) }], mesocycles: [] };
}
export function completedJointWorkoutInput(routine: Routine, durationSeconds: number, exercises: readonly CompletedExercise[]): JointCompletedWorkout {
  if (!routine.name.trim() || !Number.isInteger(durationSeconds) || durationSeconds < 0 || durationSeconds > 18_000) throw new Error('This completed workout cannot be shared.');
  return { routineName: routine.name.trim(), durationSeconds, exercises: exercises.map((exercise) => ({ name: exercise.name.trim(), muscleGroupIds: [...new Set(exercise.muscleGroupIds ?? [])].sort(), sets: exercise.sets.map(({ weight, reps, completed }) => ({ weight, reps, completed })) })) };
}
function asCompletedWorkout(value: unknown): JointCompletedWorkout | null { if (!value || typeof value !== 'object') return null; const row = value as Record<string, unknown>; if (typeof row.routineName !== 'string' || typeof row.durationSeconds !== 'number' || !Array.isArray(row.exercises)) return null; return { routineName: row.routineName, durationSeconds: row.durationSeconds, exercises: row.exercises.flatMap((exercise) => { if (!exercise || typeof exercise !== 'object') return []; const item = exercise as Record<string, unknown>; if (typeof item.name !== 'string' || !Array.isArray(item.muscleGroupIds) || !Array.isArray(item.sets)) return []; return [{ name: item.name, muscleGroupIds: item.muscleGroupIds.filter((muscle): muscle is string => typeof muscle === 'string'), sets: item.sets.flatMap((set) => { if (!set || typeof set !== 'object') return []; const value = set as Record<string, unknown>; return typeof value.weight === 'number' && typeof value.reps === 'number' && typeof value.completed === 'boolean' ? [{ weight: value.weight, reps: value.reps, completed: value.completed }] : []; }) }]; }) }; }
function asParticipant(value: unknown): JointParticipant | null { if (!value || typeof value !== 'object') return null; const row = value as Record<string, unknown>; if (typeof row.id !== 'string' || typeof row.alias !== 'string' || !['invited', 'active', 'completed', 'declined'].includes(String(row.status))) return null; const workout = asCompletedWorkout(row.workout); return { id: row.id, alias: row.alias, avatarId: avatarIdOrDefault(row.avatar_id), status: row.status as JointParticipantStatus, ...(row.relationship_kind === 'bro' || row.relationship_kind === 'partner' ? { relationshipKind: row.relationship_kind } : {}), ...(typeof row.visibility === 'string' && ['public', 'circle', 'private'].includes(row.visibility) ? { visibility: row.visibility as JointVisibility } : {}), ...(row.is_self === true ? { isSelf: true } : {}), ...(workout ? { workout } : {}), ...(row.can_invite_bro === true ? { canInviteBro: true } : {}) }; }
function asWorkout(value: unknown): JointWorkout | null { if (!value || typeof value !== 'object') return null; const row = value as Record<string, unknown>; if (typeof row.id !== 'string' || !row.suggested_routine || typeof row.suggested_routine !== 'object' || typeof row.created_at !== 'string') return null; return { id: row.id, ...(typeof row.initiator_id === 'string' ? { initiatorId: row.initiator_id } : {}), suggestedRoutine: row.suggested_routine as JointRoutine, createdAt: row.created_at, ...(typeof row.completed_at === 'string' ? { completedAt: row.completed_at } : {}), participants: Array.isArray(row.participants) ? row.participants.flatMap((participant) => { const mapped = asParticipant(participant); return mapped ? [mapped] : []; }) : [] }; }
export { routineSnapshot };
export async function createJointWorkout(targetId: string, routine: Routine) { const { data, error } = await client().rpc('create_joint_workout', { target: targetId, suggested_routine_input: routineSnapshot(routine) }); if (error) throw new Error(error.message); return String(data); }
export async function addJointWorkoutParticipant(workoutId: string, targetId: string): Promise<void> { const { error } = await client().rpc('add_joint_workout_participant', { workout_id: workoutId, target: targetId }); if (error) throw new Error(error.message); }
export async function respondToJointInvite(workoutId: string, accepted: boolean, routine?: Routine | JointRoutine) { const snapshot = routine && 'id' in routine ? routineSnapshot(routine) : routine; const { error } = await client().rpc('respond_joint_workout_invite', { workout_id: workoutId, accepted, routine_input: accepted ? snapshot ?? null : null }); if (error) throw new Error(error.message); }
export async function finishJointWorkout(workoutId: string, visibility: JointVisibility, completedWorkout: JointCompletedWorkout) { const { error } = await client().rpc('finish_joint_workout', { workout_id: workoutId, visibility_input: visibility, completed_workout_input: completedWorkout }); if (error) throw new Error(error.message); }
export async function touchJointWorkoutPresence(workoutId: string) { const { error } = await client().rpc('touch_joint_workout_presence', { workout_id: workoutId }); if (error) throw new Error(error.message); }
export async function sendJointWorkoutAction(workoutId: string, recipientId: string, action: JointActionKind): Promise<string> { const { data, error } = await client().rpc('send_joint_workout_action', { workout_id: workoutId, recipient: recipientId, action_input: action }); if (error) throw new Error(error.message); return String(data); }
export async function listJointWorkoutActions(workoutId: string): Promise<JointAction[]> { const { data, error } = await client().rpc('list_joint_workout_actions', { workout_id: workoutId }); if (error) throw new Error(error.message); return Array.isArray(data) ? data.flatMap((row) => { if (!row || typeof row !== 'object') return []; const item = row as Record<string, unknown>; if (typeof item.id !== 'string' || typeof item.sender_id !== 'string' || typeof item.recipient_id !== 'string' || typeof item.created_at !== 'string' || !['push', 'nice_set', 'finish_strong', 'partner_proud'].includes(String(item.action))) return []; return [{ id: item.id, senderId: item.sender_id, recipientId: item.recipient_id, action: item.action as JointActionKind, createdAt: item.created_at }]; }) : []; }
export async function listJointWorkouts(): Promise<JointWorkout[]> { const { data, error } = await client().rpc('list_joint_workouts'); if (error) throw new Error(error.message); return Array.isArray(data) ? data.flatMap((row) => { const workout = asWorkout(row); return workout ? [workout] : []; }) : []; }
export async function listJointWorkoutPosts(): Promise<Array<{ id: string; createdAt: string; participants: JointParticipant[] }>> { const { data, error } = await client().rpc('list_joint_workout_posts'); if (error) throw new Error(error.message); return Array.isArray(data) ? data.flatMap((row) => { if (!row || typeof row !== 'object') return []; const value = row as Record<string, unknown>; if (typeof value.id !== 'string' || typeof value.created_at !== 'string') return []; return [{ id: value.id, createdAt: value.created_at, participants: Array.isArray(value.participants) ? value.participants.flatMap((participant) => { const parsed = asParticipant(participant); return parsed ? [parsed] : []; }) : [] }]; }) : []; }
export async function getJointWorkoutDetail(workoutId: string): Promise<JointWorkout | null> { const { data, error } = await client().rpc('get_joint_workout_detail', { workout_id: workoutId }); if (error) throw new Error(error.message); return asWorkout(data); }
