import { ImageSourcePropType } from 'react-native';
import { AvatarId } from '../constants/avatars';

export const AVATAR_ASSETS: Record<AvatarId, ImageSourcePropType> = {
  'capybara-athlete': require('../assets/capybara-athlete.png'),
  'capybara-mark': require('../assets/avatar-capybara-mark.png'),
  capigirl: require('../assets/capigirl.png'),
  'capigirl-ponytail': require('../assets/capigirl-ponytail.png'),
  'capigirl-braid': require('../assets/capigirl-braid.png'),
  'capigirl-bob': require('../assets/capigirl-bob.png'),
  'capigirl-bun': require('../assets/capigirl-bun.png'),
  'capybro-spiky': require('../assets/capybro-spiky.png'),
  'capybro-quiff': require('../assets/capybro-quiff.png'),
  'capybro-topknot': require('../assets/capybro-topknot.png'),
  'capybro-cropped': require('../assets/capybro-cropped.png'),
  'capybro-river-tattoo': require('../assets/capybro-river-tattoo.png'),
  'capybro-beanie-headphones': require('../assets/capybro-beanie-headphones.png'),
  'capybro-cap-headphones': require('../assets/capybro-cap-headphones.png'),
  'capybro-cap-tank': require('../assets/capybro-cap-tank.png'),
  'capybro-beanie-tank': require('../assets/capybro-beanie-tank.png'),
  'capybro-red-visor': require('../assets/capybro-red-visor.png'),
  'capybro-argentina-beanie': require('../assets/capybro-argentina-beanie.png'),
  'capybro-argentina-visor': require('../assets/capybro-argentina-visor.png'),
  'capybro-boca': require('../assets/capybro-boca.png'),
  'capybro-river': require('../assets/capybro-river.png'),
  'capybro-argentina': require('../assets/capybro-argentina.png'),
  'capigirl-pink-squat': require('../assets/capigirl-pink-squat.jpeg'),
  'capigirl-purple-deadlift': require('../assets/capigirl-purple-deadlift.jpeg'),
  'capigirl-blue-squat': require('../assets/capigirl-blue-squat.jpeg'),
  'capigirl-black-pink-deadlift': require('../assets/capigirl-black-pink-deadlift.jpeg'),
  'capigirl-pink-jacket-deadlift': require('../assets/capigirl-pink-jacket-deadlift.jpeg'),
  'capigirl-black-dumbbell': require('../assets/capigirl-black-dumbbell.jpeg'),
  'capigirl-pink-dumbbell': require('../assets/capigirl-pink-dumbbell.jpeg'),
  'capigirl-purple-tee': require('../assets/capigirl-purple-tee.jpeg'),
  'capigirl-purple-sport': require('../assets/capigirl-purple-sport.jpeg'),
};
