import { ImageSourcePropType } from 'react-native';
import { ProfileFrameId } from '../constants/profileFrames';

// Vitest runs in Node, where React Native's numeric static assets are unavailable.
const testAsset = process.env.NODE_ENV === 'test' ? 0 : null;

export const PROFILE_FRAME_ASSETS: Record<ProfileFrameId, ImageSourcePropType> = {
  principiante: testAsset ?? require('../assets/profile-frames/principiante.png'),
  intermedio: testAsset ?? require('../assets/profile-frames/intermedio.png'),
  avanzado: testAsset ?? require('../assets/profile-frames/avanzado.png'),
  gymbro: testAsset ?? require('../assets/profile-frames/gymbro.png'),
  gymrat: testAsset ?? require('../assets/profile-frames/gymrat.png'),
  'g-boom': testAsset ?? require('../assets/profile-frames/g-boom.png'),
  alfa: testAsset ?? require('../assets/profile-frames/alfa.png'),
  'alfa-user': testAsset ?? require('../assets/profile-frames/alfa-user.png'),
  sigma: testAsset ?? require('../assets/profile-frames/sigma.png'),
  'brawl-rookie': testAsset ?? require('../assets/profile-frames/brawl/rookie.png'),
  'brawl-contender': testAsset ?? require('../assets/profile-frames/brawl/contender.png'),
  'brawl-challenger': testAsset ?? require('../assets/profile-frames/brawl/challenger.png'),
  'brawl-elite': testAsset ?? require('../assets/profile-frames/brawl/elite.png'),
  'brawl-apex': testAsset ?? require('../assets/profile-frames/brawl/apex.png'),
  'brawl-titan': testAsset ?? require('../assets/profile-frames/brawl/titan.png'),
  'brawl-warlord': testAsset ?? require('../assets/profile-frames/brawl/warlord.png'),
  'brawl-legend': testAsset ?? require('../assets/profile-frames/brawl/legend.png'),
  'shop-campeon-indiscutible': testAsset ?? require('../assets/profile-frames/shop/Campeon indiscutible.png'),
  'shop-heavy-duty': testAsset ?? require('../assets/profile-frames/shop/heavy_duty.png'),
  'shop-neon-vital': testAsset ?? require('../assets/profile-frames/shop/neon_vital.png'),
  'shop-alfa': testAsset ?? require('../assets/profile-frames/shop/Alfa.png'),
  'shop-la-12': testAsset ?? require('../assets/profile-frames/shop/la 12.png'),
  'shop-rosa-carmesi': testAsset ?? require('../assets/profile-frames/shop/rosa_carmesi.png'),
  'shop-millo': testAsset ?? require('../assets/profile-frames/shop/Millo.png'),
  'shop-celtic-spirit': testAsset ?? require('../assets/profile-frames/shop/Celtic-spirit.png'),
  'shop-hierro-fe-disciplina': testAsset ?? require('../assets/profile-frames/shop/Hierro, Fe y Disciplina..png'),
  'shop-yo-soy-el-huno': testAsset ?? require('../assets/profile-frames/shop/yo_soy_el-Huno.png'),
  'shop-spqr': testAsset ?? require('../assets/profile-frames/shop/SPQR.png'),
  'shop-fuerza-rinoceronte': testAsset ?? require('../assets/profile-frames/shop/fuerzade_rinho.png'),
  'shop-fuerza-pantera': testAsset ?? require('../assets/profile-frames/shop/fuerzade_pantera.png'),
  'shop-diamond-fit': testAsset ?? require('../assets/profile-frames/shop/Diamond_fit.png'),
  'shop-ruby-fit': testAsset ?? require('../assets/profile-frames/shop/Ruby_fit.png'),
  'shop-valhalla-training': testAsset ?? require('../assets/profile-frames/shop/Vallhala_trining.png'),
  'shop-aurora-fitness': testAsset ?? require('../assets/profile-frames/shop/aurora-fitnes.png'),
  'shop-holy-fit': testAsset ?? require('../assets/profile-frames/shop/holy-fit.png'),
  'shop-medjay-core': testAsset ?? require('../assets/profile-frames/shop/Medjay_core.png'),
  'shop-fuerza-cocodrilo': testAsset ?? require('../assets/profile-frames/shop/fuerzade_cocodrilo.png'),
  'shop-fuerza-gorila': testAsset ?? require('../assets/profile-frames/shop/fuerzade_gorila.png'),
  'shop-elegante-sport': testAsset ?? require('../assets/profile-frames/shop/elegante-sport.png'),
  'shop-banzai': testAsset ?? require('../assets/profile-frames/shop/Banzai.png'),
  'shop-neon-gym': testAsset ?? require('../assets/profile-frames/shop/Neon-Gym_sys.png'),
  'shop-fuerza-elefante': testAsset ?? require('../assets/profile-frames/shop/fuerzade_elefante.png'),
  'shop-this-is-sparta': testAsset ?? require('../assets/profile-frames/shop/this_is_sparta.png'),
  'shop-fuerza-tigre': testAsset ?? require('../assets/profile-frames/shop/fuerzade_tigre.png'),
  'shop-winter-arc': testAsset ?? require('../assets/profile-frames/shop/winter-arc.png'),
};
