// Stable IDs from taxonomia_grupos_musculares.xlsx; display fallback for offline/public snapshots.
export const BODY_CATALOG_LABELS: Readonly<Record<string, string>> = {
  "GM-001": "Cuerpo",
  "GM-010": "Tren superior",
  "GM-020": "Tren inferior",
  "GM-030": "Core y tronco",
  "GM-100": "Pecho",
  "GM-101": "Pectoral mayor",
  "GM-102": "Pectoral mayor porción clavicular",
  "GM-103": "Pectoral mayor porción esternocostal",
  "GM-104": "Pectoral mayor porción inferior",
  "GM-105": "Pectoral clavicular",
  "GM-110": "Hombros",
  "GM-111": "Deltoides",
  "GM-112": "Deltoides anterior",
  "GM-113": "Deltoides lateral",
  "GM-114": "Deltoides posterior",
  "GM-115": "Manguito rotador",
  "GM-116": "Supraespinoso",
  "GM-117": "Infraespinoso",
  "GM-118": "Redondo menor",
  "GM-120": "Espalda",
  "GM-121": "Dorsales",
  "GM-122": "Dorsal ancho",
  "GM-123": "Redondo mayor",
  "GM-124": "Espalda media",
  "GM-125": "Romboides",
  "GM-126": "Trapecio",
  "GM-127": "Trapecio superior",
  "GM-128": "Trapecio medio",
  "GM-129": "Trapecio inferior",
  "GM-130": "Espalda baja",
  "GM-131": "Erectores espinales",
  "GM-132": "Cuadrado lumbar",
  "GM-133": "Elevador de la escápula",
  "GM-140": "Brazos",
  "GM-141": "Bíceps y flexores del codo",
  "GM-142": "Bíceps braquial",
  "GM-143": "Braquial",
  "GM-144": "Braquiorradial",
  "GM-145": "Tríceps",
  "GM-146": "Tríceps braquial",
  "GM-147": "Tríceps cabeza larga",
  "GM-148": "Tríceps lateral y medial",
  "GM-149": "Antebrazos",
  "GM-150": "Extensores del antebrazo",
  "GM-151": "Agarre",
  "GM-160": "Estabilizadores escapulares",
  "GM-161": "Serrato anterior",
  "GM-162": "Rotadores externos",
  "GM-200": "Glúteos",
  "GM-201": "Glúteo mayor",
  "GM-202": "Glúteo medio",
  "GM-203": "Glúteo menor",
  "GM-210": "Cuádriceps",
  "GM-220": "Isquiosurales",
  "GM-221": "Isquios",
  "GM-230": "Aductores",
  "GM-231": "Grácil",
  "GM-232": "Pectíneo",
  "GM-240": "Abductores de cadera",
  "GM-241": "Tensor de la fascia lata",
  "GM-250": "Pantorrillas",
  "GM-251": "Gastrocnemio",
  "GM-252": "Sóleo",
  "GM-260": "Tibial anterior",
  "GM-300": "Abdominales",
  "GM-301": "Recto abdominal",
  "GM-302": "Oblicuos",
  "GM-303": "Core",
  "GM-304": "Core anterior",
  "GM-305": "Core profundo",
  "GM-310": "Flexores de cadera"
};
