-- Release gift is claimed once per account through the existing reward ledger.
insert into public.release_announcements(version, release_sequence, title, message, features, fixes, reward_gems)
values (
  '0.8.0',
  10,
  'Tu entrenamiento, tu evolución y tu comunidad',
  'Gracias por ser parte de la beta de GymBro. Sumamos herramientas para entrenar, seguir tu evolución y compartir tus logros. Te regalamos 1000 gemas por acompañarnos.',
  '["Editor de rutinas unificado con borradores recuperables, buscador de ejercicios y configuración de series, descansos, RIR y RPE.", "Prescripciones por repeticiones o tiempo, peso corporal, carga añadida y asistencia; soporte de dropsets y series de descarga.", "Mesociclos con sesiones planificadas, reprogramación, recuperación de sesiones y seguimiento de evolución entre semanas.", "Versiones de rutinas y planes que conservan el historial de lo que realmente entrenaste.", "Publicación e importación de planes compartidos con su procedencia y estructura completas.", "Entrenamientos individuales sin conexión, sincronización posterior y recuperación del entrenamiento al volver a la app.", "Continuidad del entrenamiento entre dispositivos y mejor recuperación de sesiones online y conjuntas.", "Registro rápido de series y esfuerzo real RIR/RPE, separado del objetivo de la rutina.", "Récords personales comparables de carga, repeticiones y volumen, con recompensas en gemas según el contexto.", "Nuevo cierre de entrenamiento con celebración de XP, niveles y gemas, vista previa y selección de récords para publicar.", "Cierres pendientes recuperables desde Entrenar y publicación conjunta cuando los participantes completan su revisión.", "Resumen semanal de actividad, volumen, densidad y esfuerzo registrado.", "Perfil de atleta renovado con accesos al historial, progreso y preferencias.", "Mapas musculares de frente y espalda en perfiles y publicaciones, con detalle de los grupos trabajados.", "Volumen muscular en períodos de 7, 28 y 90 días, comparación con el período anterior y objetivos con privacidad independiente.", "Evolución corporal por día con peso, medidas privadas e historial.", "Fotos de evolución en Android/iOS con guías de pose, cuenta regresiva y comparación entre fechas. Las fotos se guardan en el dispositivo; las medidas se sincronizan con tu cuenta.", "Reglas de relación GymCrush y mejoras en la experiencia de comunidad.", "1000 gemas de regalo por cuenta: gracias por acompañarnos y ayudarnos a mejorar GymBro durante la beta."]'::jsonb,
  '["Mayor protección del progreso guardado ante cierres, reconexiones y respuestas tardías.", "Sincronización y cancelación más confiables de entrenamientos conjuntos, sin duplicar publicaciones ni recompensas al reintentar.", "Las recompensas del entrenamiento se conservan aunque no selecciones sus récords para publicar.", "Cálculo muscular más preciso: distingue series directas e indirectas y excluye calentamientos, series omitidas y datos inválidos.", "Mejoras en temporizadores, continuidad del mesociclo y navegación entre sesión, resumen y publicación.", "Mejoras de visualización en web, notificaciones, estados de carga y accesibilidad; menos animaciones en pantallas inactivas."]'::jsonb,
  1000
);

insert into public.release_reward_campaigns(version, gem_amount, idempotency_key)
values ('0.8.0', 1000, 'release:0.8.0:1000-gems');
